import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const pocDir = path.dirname(fileURLToPath(import.meta.url));
const metadataPath = path.join(pocDir, 'pages.json');
const outputDir = path.join(pocDir, 'generated');
const assetPrefix = '../../../www';

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('"', '&quot;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

function prefixedAsset(value) {
  if (!value) {
    return value;
  }

  return `${assetPrefix}/${value}`;
}

function attrs(attributes) {
  return Object.entries(attributes)
    .filter(([, value]) => value !== undefined && value !== null)
    .map(([key, value]) => `${key}="${escapeHtml(value)}"`)
    .join(' ');
}

function normalizeExtraAttrs(extraAttrs = {}) {
  return Object.fromEntries(
    Object.entries(extraAttrs).map(([key, value]) => {
      if (typeof value === 'string' && value.startsWith('media/')) {
        return [key, prefixedAsset(value)];
      }

      return [key, value];
    })
  );
}

function renderHead(page) {
  return `    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${escapeHtml(page.title)}</title>
    <link rel="stylesheet" href="${assetPrefix}/styles.css">
    <link rel="stylesheet" href="${assetPrefix}/common_tumski.css">
    <link rel="stylesheet" href="${assetPrefix}/${escapeHtml(page.stylesheet)}">
    <link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,200&display=swap" rel="stylesheet">
    <script src="${assetPrefix}/i18n.js"></script>
    <script src="${assetPrefix}/common.js"></script>
    <script src="${assetPrefix}/arrow_handlers.js"></script>
    <script src="${assetPrefix}/book_paths.js"></script>
    <script src="${assetPrefix}/common_buttons.js"></script>
    <script src="${assetPrefix}/language_menu.js"></script>
    <script src="${assetPrefix}/map_modal.js"></script>
    <script type="module" src="${assetPrefix}/tumski_cathedral_handler.js"></script>
    <script type="module" src="${assetPrefix}/map_points.js"></script>`;
}

function renderHints(page) {
  if (!page.hints) {
    return '';
  }

  return `    <div id="musicHint" class="music-hint" data-i18n="music.hint"></div>
    <div id="animationHint" class="animation-hint" data-i18n="animation.hint"></div>

`;
}

function renderMarker(marker) {
  const markerAttrs = {
    class: 'map-mark',
    id: marker.id,
    'data-x-desktop': marker.xDesktop,
    'data-y-desktop': marker.yDesktop,
    'data-x-mobile': marker.xMobile,
    'data-y-mobile': marker.yMobile,
    ...normalizeExtraAttrs(marker.extraAttrs)
  };
  const paperaAttrs = {
    class: 'papera-image',
    src: marker.paperaSrc ? prefixedAsset(marker.paperaSrc) : undefined,
    alt: 'Papera'
  };
  const textAttrs = {
    class: 'tumski-text',
    id: marker.textId,
    'data-i18n': marker.i18n
  };

  return `    <!-- ${escapeHtml(marker.comment)} -->
    <div class="map-mark-area">
        <div ${attrs(markerAttrs)}></div>
        <div class="content-wrapper">
            <img ${attrs(paperaAttrs)}>
            <div ${attrs(textAttrs)}></div>
        </div>
        <audio id="${escapeHtml(marker.audioId)}" src="${assetPrefix}/media/opening-a-book.wav"></audio>
    </div>`;
}

function renderArrow(arrow) {
  const cursorAttrs = {
    class: arrow.cursorClass,
    'data-x-desktop': arrow.xDesktop,
    'data-y-desktop': arrow.yDesktop,
    'data-x-mobile': arrow.xMobile,
    'data-y-mobile': arrow.yMobile,
    'data-next-page': arrow.nextPage,
    'data-prev-page': arrow.prevPage
  };
  const areaAttrs = {
    class: arrow.areaClass,
    'data-x-desktop': arrow.areaXDesktop,
    'data-y-desktop': arrow.areaYDesktop,
    'data-x-mobile': arrow.areaXMobile,
    'data-y-mobile': arrow.areaYMobile
  };

  return `                    <!-- ${escapeHtml(arrow.comment)} -->
                    <div ${attrs(cursorAttrs)}></div>
                    <div ${attrs(areaAttrs)}></div>`;
}

function renderArrows(arrows, layer) {
  return arrows
    .filter((arrow) => arrow.layer === layer)
    .map(renderArrow)
    .join('\n\n');
}

function renderPage(page) {
  return `<!DOCTYPE html>
<!-- Generated by tools/template-poc/generate.mjs. Production pages are unchanged. -->
<html lang="ru">
<head>
${renderHead(page)}
</head>
<body>
${renderHints(page)}${page.markers.map(renderMarker).join('\n\n')}

    <div class="scene">
        <div class="image-container" data-map-point="${escapeHtml(page.mapPoint)}">
            <div class="image-scroll-wrapper">
                <div class="image">
${renderArrows(page.arrows, 'image')}
                </div>
${renderArrows(page.arrows, 'scroll-wrapper')}
            </div>
        </div>
        <div class="next-image-container"></div>
    </div>

    <script type="module" src="${assetPrefix}/tumski_init.js"></script>
</body>
</html>
`;
}

const metadata = JSON.parse(await readFile(metadataPath, 'utf8'));

await mkdir(outputDir, { recursive: true });

for (const page of metadata.pages) {
  await writeFile(path.join(outputDir, page.output), renderPage(page));
}

console.log(`Template POC generated ${metadata.pages.length} pages -> ${path.relative(process.cwd(), outputDir)}`);
